// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type FeatureRequest struct {
	ID          pgtype.UUID        `json:"id"`
	AuthorID    pgtype.UUID        `json:"author_id"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	VoteCount   int32              `json:"vote_count"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PasswordHash *string            `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Vote struct {
	UserID    pgtype.UUID        `json:"user_id"`
	RequestID pgtype.UUID        `json:"request_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
